language: R
sudo: required
warnings_are_errors: true

branches:
  only:
    - master

### For Linux
os:
  - linux

env:
  global:
    - CRAN: https://cran.rstudio.com
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

before_install:
  - sudo apt-get update -q

r_packages:
  - fda

r_check_args: --no-build-vignettes --no-manual

notifications:
  email:
    on_success: no
    on_failure: no

